baseurl = "https://karloguidoni.com/"
languageCode = "en-us"
title = "Karlo Guidoni"
theme = "blackburn"
author = "Karlo Guidoni"
copyright = 'Licence: <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA</a>'
canonifyurls = true
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  title = "Karlo Guidoni"
  # Shown in the home page
  subtitle = ""
  # brand = "Karlo Guidoni Martins"
  googleAnalytics = 'UA-151898291-2'
  # disqus = "kguidonimartins"
  # CSS name for highlight.js
  highlightjs = "github"
  githubsource = "https://github.com/kguidonimartins/kguidonimartins/blob/master/content/"
  dateFormat = "02-01-2006"
  summary_length = 20

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "TIL"
    pre = "<i class='fas fa-pencil-alt fa-fw'></i>"
    weight = 3
    identifier = "til"
    url = "/til/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tags"
    url = "/tags/"
#  [[menu.main]]
#    name = "Bio"
#    pre = "<i class='fa fa-id-card fa-fw'></i>"
#    weight = 4
#    identifier = "bio"
#    url = "/bio/"
#  [[menu.main]]
#    name = "Talks"
#    pre = "<i class='fa fa-microphone fa-fw'></i>"
#    weight = 6
#    identifier = "talks"
#    url = "/talks/"
#  [[menu.main]]
#    name = "CV"
#    pre = "<i class='fa fa-paperclip fa-fw'></i>"
#    weight = 6
#    identifier = "cv"
#    url = "/cv/"
#   [[menu.main]]
#     name = "Publications"
#     pre = "<i class='fa fa-newspaper-o fa-fw'></i>"
#     weight = 7
#     identifier = "papers"
#     url = "/papers/"
#  [[menu.main]]
#    name = "Portfolio"
#    pre = "<i class='fa fa-bar-chart fa-fw'></i>"
#    weight = 8
#    url = "/portfolio/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-question-circle fa-fw'></i>"
    weight = 9
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
#  facebook = ""
#  instagram = ""
  github = "kguidonimartins"
#  stackoverflow = "5974372"
#  linkedin = "kguidonimartins"
  email = "kguidonimartins"
#  keybase = ""
  orcid = "0000-0002-8458-8467"
#  researchgate = "Karlo_Gregorio_Guidoni-Martins"
#  twitter = "kguidonimartins"
#  til = "vimwiki"

[markup.highlight]
  codeFences = true
  hl_Lines = ""
  lineNumbersInTable = true
  noClasses = true
  style = "tango"
  tabWidth = 2
  # lineNoStart = 1
  # lineNos = true
